### PR TITLE
deps: include PHP 8.1 as well

### PR DESCRIPTION
**Pull request by pixeldev**
Tell us about why this change is necessary:
- Are you fixing a bug or providing a failing unit test to demonstrate a bug?
  - How do you reproduce it? Try to install with composer this package using PHP 8.1.
  - What did you expect to happen? Add this package to composer.json and run composer upgrade successfully.
  - What actually happened? A composer message showing that your PHP 8.1 version isn't supported.

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
`composer.lock` needs updating.

**Comment by pixeldev** [comment]
How to solve it? ): I really need this

**Comment by froschdesign** [comment]
@pixeldev
> How to solve it?

Check the failure on the CI checks: https://github.com/laminas/laminas-migration/runs/6777118925?check_suite_focus=true#step:3:308
It looks like that a newer version of symfony/console is needed.

**Comment by Ocramius** [comment]
Was this closed on purpose, @pixeldev ?

**Pull request closed without merging**
